### ISSUE TITLE
 About generating the LasHeR dataset five attribute branches

### ISSUE THREAD

**Issue by 972821054** [yangmengmeng1997/APFNet#8]
Hello, are you training the code on the LasHeR dataset again? How did you divide the dataset attribute branches? If possible, can you provide the partitioned dataset or code for partitioning? I will be very grateful!

**Comment by yangmengmeng1997** [comment]
Hello！Since the challenge annotations of GTOT and RGBT 234 are manually annotated frame by frame, so they can be trained, LasHeR does not label challenge information frame by frame, so it cannot be used for training. You can refer to ADRNet's simulation challenge data generation method to generate the challenge data you need.&nbsp;

@article{Zhang_IJCV21_ADRNet,
author = {Pengyu Zhang and Dong Wang and Huchuan Lu and Xiaoyun Yang},
title = {Learning Adaptive Attribute-Driven Representation for Real-Time RGB-T Tracking},
journal = IJCV,
volume = {129},
pages = {2714–2729},
year = {2021}
}


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangmengmeng1997/APFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 中午1:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yangmengmeng1997/APFNet]  About generating the LasHeR dataset five attribute branches (Issue #8)





 
Hello, are you training the code on the LasHeR dataset again? How did you divide the dataset attribute branches? If possible, can you provide the partitioned dataset or code for partitioning? I will be very grateful!
